apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-dynamic
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-dynamic
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    purpose: ebs-dynamic-practice
    environment: dev
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1b
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
       - name: persistent-storage
         mountPath: /usr/share/nginx/html
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: ebs-dynamic
---
apiVersion: v1
kind: Service
metadata:
  name: ebs-dynamic-pod-lb
  labels:
    purpose: ebs-dynamic-practice
    environment: dev
spec:
  type: LoadBalancer
  selector:
    purpose: ebs-dynamic-practice
    environment: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80