apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: COURSE
      valueFrom:
        configMapKeyRef:
          name: course-config
          key: COURSE
    - name: SKILLS
      valueFrom:
        configMapKeyRef:
          name: course-config
          key: SKILLS