apiVersion: v1
kind: Secret
metadata:
  name: secret-sample
data:
  Name: UGF2YW4gS3VtYXIgRGl2aQo=
  ROLE: RGV2T3BzIEVuZ2luZWVyCg==
---
apiVersion: v1
kind: Pod
metadata:
  name: secretRef
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - secretRef:
        name: secret-sample